"""Mad-libs style session slugs: adjective-adjective-animal.

Slugs identify chat sessions in the delta lake. The grammar is
``{animal-quality-adjective}-{animal-quality-adjective}-{animal}`` with
slot uniqueness enforced (adj1 != adj2). Read as a sentence fragment:

    quiet-tired-otter
    mean-tepid-mosquito
    feral-shy-heron

Separability matters more than memorization — the agent searches by
exact tag (``chat:<slug>``), so length is free. Beauty and low
collision probability are what we optimize for.

Combinatorics: |ADJ| * (|ADJ|-1) * |ANIMALS| ≈ 10.6M with current lists.
"""

from __future__ import annotations

import random
from typing import Any

# ── Wordlists ────────────────────────────────────────────────────────────

# Animal-quality adjectives — traits, moods, conditions, temperaments.
# NOT colors, textures, materials, or weather. Each word must answer
# "what is the animal like?" in a way that would make sense on an otter
# or a shrew.
ADJECTIVES: tuple[str, ...] = (
    # Mood (55)
    "quiet",
    "loud",
    "calm",
    "restless",
    "cheerful",
    "grumpy",
    "sullen",
    "merry",
    "glum",
    "dour",
    "chipper",
    "peevish",
    "jovial",
    "morose",
    "melancholy",
    "content",
    "moody",
    "sulky",
    "sunny",
    "giddy",
    "buoyant",
    "dejected",
    "elated",
    "forlorn",
    "gleeful",
    "crabby",
    "huffy",
    "mopey",
    "brooding",
    "perky",
    "snappish",
    "testy",
    "cross",
    "irritable",
    "sour",
    "bitter",
    "serene",
    "somber",
    "wistful",
    "peaceful",
    "restive",
    "wary",
    "jittery",
    "edgy",
    "tense",
    "frantic",
    "frazzled",
    "steady",
    "anxious",
    "eager",
    "apathetic",
    "indifferent",
    "stoic",
    "plaintive",
    "smug",
    # Energy (30)
    "tired",
    "sleepy",
    "drowsy",
    "groggy",
    "lethargic",
    "weary",
    "exhausted",
    "sluggish",
    "dozing",
    "spry",
    "lively",
    "peppy",
    "alert",
    "vibrant",
    "brisk",
    "nimble",
    "zippy",
    "listless",
    "languid",
    "dozy",
    "sprightly",
    "bouncy",
    "springy",
    "vigorous",
    "feisty",
    "wiry",
    "frisky",
    "fidgety",
    "jumpy",
    "skittish",
    # Temperament (35)
    "gentle",
    "fierce",
    "meek",
    "bold",
    "timid",
    "brave",
    "shy",
    "feral",
    "tame",
    "wild",
    "docile",
    "placid",
    "flighty",
    "stormy",
    "savage",
    "ferocious",
    "mild",
    "harsh",
    "rough",
    "tender",
    "fragile",
    "hardy",
    "tough",
    "delicate",
    "scrappy",
    "rowdy",
    "mellow",
    "chill",
    "uptight",
    "relaxed",
    "vicious",
    "hostile",
    "benign",
    "pacific",
    "rambunctious",
    # Social (20)
    "friendly",
    "aloof",
    "affectionate",
    "distant",
    "loyal",
    "cagey",
    "trusting",
    "sociable",
    "lonely",
    "solitary",
    "clingy",
    "standoffish",
    "gregarious",
    "reclusive",
    "bashful",
    "brash",
    "haughty",
    "snooty",
    "gallant",
    "courteous",
    # Intellect (20)
    "clever",
    "cunning",
    "sly",
    "foolish",
    "wise",
    "dopey",
    "canny",
    "naive",
    "dimwitted",
    "crafty",
    "shrewd",
    "simple",
    "dense",
    "brainy",
    "savvy",
    "ingenious",
    "witty",
    "dull",
    "sharp",
    "bumbling",
    # Condition (30)
    "hungry",
    "sated",
    "parched",
    "tepid",
    "feverish",
    "chilly",
    "warm",
    "cozy",
    "clammy",
    "soggy",
    "dry",
    "damp",
    "dusty",
    "muddy",
    "bedraggled",
    "tousled",
    "scruffy",
    "ragged",
    "frayed",
    "sleek",
    "glossy",
    "grizzled",
    "hoary",
    "downy",
    "bristly",
    "matted",
    "unkempt",
    "preened",
    "pristine",
    "rumpled",
    # Personality (28)
    "greedy",
    "jealous",
    "proud",
    "humble",
    "stubborn",
    "obedient",
    "rebellious",
    "gruff",
    "curious",
    "incurious",
    "demure",
    "pompous",
    "modest",
    "vain",
    "earnest",
    "sincere",
    "devious",
    "honest",
    "mischievous",
    "impish",
    "puckish",
    "roguish",
    "saucy",
    "coy",
    "boastful",
    "reserved",
    "forthright",
    "furtive",
    # Physical demeanor (20)
    "lanky",
    "stout",
    "portly",
    "scrawny",
    "plump",
    "lithe",
    "clumsy",
    "graceful",
    "awkward",
    "limber",
    "stiff",
    "supple",
    "burly",
    "sturdy",
    "spindly",
    "gangly",
    "hunched",
    "upright",
    "compact",
    "sprawling",
)

# Recognizable animals — mammals, birds, fish, reptiles, amphibians, insects.
# Each should be known well enough that a non-biologist hears it and pictures
# the creature. No cryptic zoology.
ANIMALS: tuple[str, ...] = (
    # Mammals — terrestrial (55)
    "otter",
    "badger",
    "shrew",
    "bison",
    "elk",
    "hare",
    "fox",
    "wolf",
    "bear",
    "deer",
    "rabbit",
    "mouse",
    "rat",
    "hedgehog",
    "ferret",
    "weasel",
    "mink",
    "skunk",
    "raccoon",
    "opossum",
    "squirrel",
    "chipmunk",
    "beaver",
    "porcupine",
    "armadillo",
    "sloth",
    "lemur",
    "monkey",
    "ape",
    "gorilla",
    "chimp",
    "baboon",
    "marmoset",
    "lion",
    "tiger",
    "leopard",
    "cheetah",
    "jaguar",
    "panther",
    "cougar",
    "lynx",
    "bobcat",
    "ocelot",
    "serval",
    "caracal",
    "meerkat",
    "mongoose",
    "hyena",
    "jackal",
    "coyote",
    "dingo",
    "panda",
    "kangaroo",
    "koala",
    "wombat",
    # Mammals — hoofed & herd (15)
    "horse",
    "pony",
    "donkey",
    "mule",
    "zebra",
    "llama",
    "alpaca",
    "camel",
    "yak",
    "ram",
    "goat",
    "sheep",
    "boar",
    "stag",
    "moose",
    # Mammals — marine (10)
    "seal",
    "walrus",
    "whale",
    "dolphin",
    "orca",
    "porpoise",
    "manatee",
    "narwhal",
    "beluga",
    "sealion",
    # Birds — songbirds & common (30)
    "sparrow",
    "finch",
    "wren",
    "robin",
    "swallow",
    "warbler",
    "thrush",
    "starling",
    "mockingbird",
    "cardinal",
    "chickadee",
    "nuthatch",
    "titmouse",
    "junco",
    "lark",
    "oriole",
    "goldfinch",
    "bluebird",
    "waxwing",
    "jay",
    "magpie",
    "crow",
    "raven",
    "rook",
    "grackle",
    "blackbird",
    "cowbird",
    "vireo",
    "kinglet",
    "thrasher",
    # Birds — raptors & waterfowl (25)
    "eagle",
    "hawk",
    "falcon",
    "osprey",
    "kestrel",
    "vulture",
    "condor",
    "owl",
    "heron",
    "egret",
    "ibis",
    "crane",
    "stork",
    "pelican",
    "loon",
    "grebe",
    "cormorant",
    "albatross",
    "gull",
    "tern",
    "puffin",
    "auk",
    "kiwi",
    "toucan",
    "parrot",
    # Birds — ground & flightless (8)
    "emu",
    "ostrich",
    "peacock",
    "pheasant",
    "quail",
    "partridge",
    "dove",
    "pigeon",
    # Reptiles & amphibians (18)
    "snake",
    "viper",
    "python",
    "cobra",
    "mamba",
    "gecko",
    "iguana",
    "chameleon",
    "lizard",
    "turtle",
    "tortoise",
    "alligator",
    "crocodile",
    "newt",
    "salamander",
    "axolotl",
    "toad",
    "frog",
    # Fish & aquatic (15)
    "salmon",
    "trout",
    "bass",
    "pike",
    "cod",
    "tuna",
    "mackerel",
    "marlin",
    "shark",
    "ray",
    "eel",
    "carp",
    "perch",
    "minnow",
    "koi",
    # Invertebrates (22)
    "shrimp",
    "lobster",
    "crab",
    "octopus",
    "squid",
    "jellyfish",
    "seahorse",
    "starfish",
    "urchin",
    "mosquito",
    "butterfly",
    "moth",
    "bee",
    "wasp",
    "hornet",
    "ant",
    "beetle",
    "cricket",
    "grasshopper",
    "mantis",
    "dragonfly",
    "firefly",
)


def generate_slug(rng: random.Random | None = None) -> str:
    """Generate a random adj-adj-animal slug with slot uniqueness."""
    r = rng or random
    adj1 = r.choice(ADJECTIVES)
    # Cheap retry until adj2 != adj1. With |ADJ| ~ 220, average ~1.005 draws.
    while True:
        adj2 = r.choice(ADJECTIVES)
        if adj2 != adj1:
            break
    animal = r.choice(ANIMALS)
    return f"{adj1}-{adj2}-{animal}"


def is_slug_taken(http_client: Any, delta_url: str, headers: dict, slug: str) -> bool:
    """Return True if any delta already carries the ``chat:<slug>`` tag."""
    resp = http_client.get(
        f"{delta_url}/deltas",
        params={"tags_include": f"chat:{slug}", "limit": 1},
        headers=headers,
    )
    if resp.status_code != 200:
        # If we can't tell, assume free — the alternative is blocking on a down lake.
        return False
    data = resp.json()
    if isinstance(data, dict):
        data = data.get("deltas") or data.get("results") or []
    return bool(data)


def generate_unique_slug(
    http_client: Any,
    delta_url: str,
    headers: dict,
    *,
    max_attempts: int = 10,
    rng: random.Random | None = None,
) -> str:
    """Generate a slug unused in the lake. Retries on collision.

    With ~10M combos, collisions are vanishingly rare — max_attempts is a
    safety net, not a load-bearing retry loop.
    """
    for _ in range(max_attempts):
        slug = generate_slug(rng)
        if not is_slug_taken(http_client, delta_url, headers, slug):
            return slug
    # Absurd fallback: append a 3-letter marker. Should never fire.
    r = rng or random
    suffix = "".join(r.choice("abcdefghjkmnpqrstuvwxyz") for _ in range(3))
    return f"{generate_slug(rng)}-{suffix}"
